// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiFpX4SlZBbHuaHmfPcFxL8Z6r1jxwVzY',
    appId: '1:238812859436:web:842bc724d5a2fad7fe5589',
    messagingSenderId: '238812859436',
    projectId: 'ai-summarizer-ab782',
    authDomain: 'ai-summarizer-ab782.firebaseapp.com',
    storageBucket: 'ai-summarizer-ab782.firebasestorage.app',
    measurementId: 'G-EL94H2TMHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4YOTCVVPUJK4brDpZu8s9i4Fpi9qqvvI',
    appId: '1:238812859436:android:c6d9cba63e49c51dfe5589',
    messagingSenderId: '238812859436',
    projectId: 'ai-summarizer-ab782',
    storageBucket: 'ai-summarizer-ab782.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzfsnUeEEU4P-arkPgLLFOahlkvOcrfY4',
    appId: '1:238812859436:ios:3be0982eac5eea02fe5589',
    messagingSenderId: '238812859436',
    projectId: 'ai-summarizer-ab782',
    storageBucket: 'ai-summarizer-ab782.firebasestorage.app',
    iosBundleId: 'com.example.aiTextSummrizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzfsnUeEEU4P-arkPgLLFOahlkvOcrfY4',
    appId: '1:238812859436:ios:3be0982eac5eea02fe5589',
    messagingSenderId: '238812859436',
    projectId: 'ai-summarizer-ab782',
    storageBucket: 'ai-summarizer-ab782.firebasestorage.app',
    iosBundleId: 'com.example.aiTextSummrizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiFpX4SlZBbHuaHmfPcFxL8Z6r1jxwVzY',
    appId: '1:238812859436:web:d6bc6a75d59572d1fe5589',
    messagingSenderId: '238812859436',
    projectId: 'ai-summarizer-ab782',
    authDomain: 'ai-summarizer-ab782.firebaseapp.com',
    storageBucket: 'ai-summarizer-ab782.firebasestorage.app',
    measurementId: 'G-RB1FPYL8ES',
  );
}
